version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./data/rabbitmq/:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  mongo:
    image: mongo:4.0
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111
