name: Test

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install packages
        run: |
            sudo apt-get update
            sudo apt-get install -y ffmpeg aria2

      - name: Install dependencies
        run: poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Run tests and collect coverage
        run: pytest --cov --suppress-tests-failed-exit-code

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)
